### ISSUE TITLE
ISS-202 : after updating GNUC to 3, memcached doesn't compile anymore

### ISSUE THREAD

**Issue by stormalf** [stormalf/chibicc#120]
after updating GNUC to 3, memcached doesn't compile anymore :

./xxhash.h:3024: error: #    define XXH_PREFETCH(ptr)  __builtin_prefetch((ptr), 0 /* rw==read */, 3 /* locality */)
                                                       ^ parse.c 6748: in primary : implicit declaration of function

**Comment by stormalf** [comment]
it will be solved in 1.0.23.3
